---
title: "R Notebook"
---

```{r}
library(reactable)
library(gt)
library(tidygeocoder)
```

```{r}
citation_strings <-
  citations |>
  filter(stringr::str_detect(DOI, "doi")) |>
  pull(metadata) |>
  purrr::map_chr(function(article){
    
    # if(article == "https://doi.org/10.3394/0380-1330(2007)33[93:ETSOLO]2.0.CO;2")
    
    if(!is.null(article$authors)){
      author_string <- article$authors |>
        purrr::map_chr(function(author){
          paste0(author$given," ",author$family)
        }) |>
        paste0(collapse = ", ")
      
      author_string <- paste0(author_string)
    } else{
      author_string <- ""
    }
    
    year_string <- paste0("(", lubridate::year(article$date_time),")")
    
    title_string <- paste0("<strong>",article$title,"</strong>")
    
    link_string <- paste0("https://doi.org/", article$DOI)
    link_string <- paste0("<a href='",link_string,"' target='_blank'>",link_string,"</a>")
    
    paste0(author_string,". ",
           year_string,". ",
           title_string,". ",
           link_string,".")
    
  })



reactable::reactable(data.frame("x" = citation_strings),
                     columns = list(
                       x = colDef(html = TRUE,name = "")
                     ),
                     sortable = FALSE,
                     showSortable = FALSE)
```

```{r}

```

```{r}
locations_by_doi_combined |>
  arrange(Location)
```

