---
title: ""
title-block: none
format: 
  html:
    toc: false
    embed-resources: true
---

```{r}
#| include: false
source("plotly_icon_svgs.R")
```

Tämä välilehti näyttää interaktiivisen hajontakuvion datasta.

* Jokainen piste edustaa yksittäistä havaintoa selviytymisasteesta (prosentteina) suhteessa tiamiinikonsentraatioon (nmol/g).
* Käyrät ja varjostetut alueet näyttävät sovitetut mallit ja niiden epävarmuuden. Jokaiselle lajille on oma malli.
* Pisteet ja käyrät on väritetty lajin mukaan.
* Kuvio on interaktiivinen. Napsauta ja vedä zoomataksesi. Vie hiiri pisteen päälle nähdäksesi lisätietoja.
* Kuvion yläpuolella oleva työkalupalkki mahdollistaa zoomauksen, siirtämisen, näkymän palauttamisen ja kuvan viennin.
  - `r icons$camera` Tallenna nykyinen näkymä .png-tiedostona
  - `r icons$zoom_box` Napsauta ja vedä zoomataksesi tiettyyn alueeseen kaaviossa.
  - `r icons$pan` Napsauta ja vedä siirtääksesi kaaviota ilman zoomausta.
  - `r icons$zoom_plus` Zoomaa kaavion keskelle.
  - `r icons$zoom_minus` Loitonna kaavion keskeltä.
  - `r icons$home` Palauta kaavio alkuperäiseen näkymään.
  - `r icons$tooltip_basic` Näytä lähimmän tietopisteen tiedot.
  - `r icons$tooltip_compare` Näytä kaikkien sarjojen arvot samalla tiamiinitasolla osoittamalla.

Voit myös lisätä omia tietojasi hajontakuvioon:

* Valitse laji datapisteellesi.
* Syötä tiamiinikonsentraatio (pakollinen) ja havaittu selviytymisaste (valinnainen).
* Jos syötät havaitun selviytymisasteen, se näytetään mustana pisteenä kuviossa.
* Sovellus laskee myös ennustetun selviytymisasteen valitun lajin mallin perusteella. Ennustettu arvo näytetään mustana pisteenä, jossa on katkoviivareunus.
* Kun lisäät tietoja, kuvion alle ilmestyy yhteenvetotaulukko.

Voit viedä taulukon CSV-tiedostona napsauttamalla "Vie taulukko CSV-muodossa" -painiketta.

Sivupalkin suodattimet vaikuttavat myös tähän välilehteen.

Esimerkiksi, kun valitset lajin, näkyvät vain kyseisen lajin pisteet ja käyrät.
